spring:
  application:
    name: bankingapp-notification-service

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST:localhost}:9092

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${REGISTRY_SERVER_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 9001

custom-message: "This is message from config file of bankingapp-notification-service via config server."
