spring:
  application:
    name: bankingapp-account-service
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST:localhost}:9092

  # Database configuration
  datasource:
    # for postgres db
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:5432/capstone
    username: postgres
    password: postgres

    # for h2 db
#    url: jdbc:h2:mem:capstone
#    username: accounts
#    password:
#    initialization-mode: always
#    schema: classpath:/schema.sql
#    data: classpath:/data.sql


  #Hibernate Configuration - database configuration is also required
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_SERVER_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 7070

custom-message: "This is message from config file of bankingapp-account-service via config server."
