spring:
  application:
    name: bankingapp-gateway-service
  cloud:
    gateway:
      routes:
        - id: accountsRoute
          uri: lb://bankingapp-account-service
          predicates:
            - Path=/bankingapp/api/accounts
          filters:
            - StripPrefix=2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8111

management:
  endpoints:
    web:
      exposure:
        include: "*"

custom-message: "This is message from config file of bankingapp-gateway-service via config server."
