spring:
  application:
    name: bankingapp-fundtransfer-service
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
      
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST:localhost:9092}

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_SERVER_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true      

server:
  port: 7080

custom-message: "This is message from config file of bankingapp-fundtransfer-service via config server."
